---
permalink: concept-configure-snapmanager-for-hyper-v-for-failover.html 
sidebar: sidebar 
keywords: enable, snapmanager, hyper-v, implementation, disaster, recovery, primary, secondary, host, powershell, failover, configure, configuring 
summary: ディザスタリカバリ目的でSnapManager をHyper-V環境に完全に実装できるようにするには、プライマリホストとセカンダリホストを同じ構成にし、PowerShellのみを使用してディザスタリカバリを実行できることを確認する必要があります。 
---
= フェイルオーバー用にSnapManager を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ディザスタリカバリ目的でSnapManager をHyper-V環境に完全に実装できるようにするには、プライマリホストとセカンダリホストを同じ構成にし、PowerShellのみを使用してディザスタリカバリを実行できることを確認する必要があります。

ディザスタリカバリは次のタイプのセットアップでサポートされます。

* スタンドアロンのプライマリホストとスタンドアロンのセカンダリHyper-Vホスト
* クラスタ化されたプライマリおよびセカンダリHyper-Vホスト
* プライマリとセカンダリのHyper-Vホスト上のCluster Shared Volume（CSV；クラスタ共有ボリューム）


たとえば、プライマリホスト上のクラスタ仮想マシン（VM）をクラスタVMとしてリカバリし、専用の（スタンドアロンの）VMを専用のVMとしてリカバリし、CSV VMをCSV VMとしてリカバリする必要があります。

セカンダリホスト上のLUNは、プライマリホスト上の対応するLUNと同じ方法で接続する必要があります。つまり、LUNタイプ（専用、共有、CSV）とドライブレター、マウントポイント、CSVは、プライマリホストとセカンダリホストで同じリパースポイントである必要があります。代替パスへのSANリストア処理では、セカンダリストレージへのLUNリストア処理に別のドライブレターを指定できます。


NOTE: ドライブレターまたはCSV、およびボリュームマウントポイントがサポートされます。

次に、ディザスタリカバリの基本的な設定例を示します。

* サイトA（プライマリ）には、ストレージシステム、およびスタンドアロンのHyper-VホストシステムまたはHyper-Vホストクラスタが含まれています。
+
これらのホスト上で実行されているVMは、Data ONTAP ストレージに配置されます。

* サイトB（セカンダリ）には、ストレージシステムとHyper-Vホストまたはクラスタ（プライマリと同じ）が含まれます。
* SnapDrive for WindowsとSnapManager for Hyper-Vが、サイトAとサイトBの両方にインストールされている
* SnapMirror関係は、サイトAからサイトBへと初期化されます
* サイトAでは、Hyper-V用にSnapManager に追加したHyper-Vホストまたはクラスタを、Hyper-V用のSnapManager を使用してバックアップします
+
バックアップのチェック後にSnapMirrorを更新するポリシー。バックアップが完了するたびに、セカンダリサイトが更新され、VMおよびSnapInfoコピーの新しいSnapshotコピーが作成されます。


