---
permalink: concept_snapmanager_for_hyper_v_limitations.html 
sidebar: sidebar 
keywords: important, understand, snapmanager, hyper-v, limitation 
summary: SnapManager 2.1以降のHyper-Vでは、一部の機能がサポートされないことに注意してください 
---
= SnapManager for Hyper-Vの制限事項の一覧です
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager 2.1以降のHyper-Vでは、一部の機能がサポートされないことに注意してください。

* バックアップジョブとリストアジョブのキャンセル、一時停止、再開はサポートされていません。
* ポリシーをデータセット間でコピーすることはできません。
* ロールベースアクセス制御（RBAC）はサポートされていません。
* Hyper-V Volume Shadow Copy Service（VSS；ボリュームシャドウコピーサービス）のバックアップジョブ用にSnapManager からVirtual Hard Disk（VHD；仮想ハードディスク）を除外することはできません。
* バックアップコピーからの単一ファイルのリストアは、標準ではサポートされていません。
* バージョン間の管理はサポートされていません。たとえば、クライアントコンソール1.2を使用してHyper-V用のSnapManager 2.0を管理することはできず、その逆もできません。
* Hyper-V仮想マシン（VM）のリストアを開始したときに、同じVMの別のバックアップまたはリストアが進行中の場合は、この処理は失敗します。
* crash-consistentバックアップコピーからの削除されたVMのリストアは、Windows Server 2012でのみサポートされています。
* フェイルオーバークラスタのノードごとに異なるバージョンのSnapManager for Hyper-Vを実行することはできません。
* Hyper-VのSnapManager 2.1からのリバートはサポートされていません。
* 仮想マシンのバックアップまたはリストア中にユーザがクラスタ所有権ノードを変更した場合、仮想マシンのバックアップまたはリストアジョブはサポートされません。
* 混在モードのバックアップ（CSV 2.0ボリュームおよびSMB共有上のファイルを含む仮想マシン）はサポートされません。
* Windows Server 2012を使用してVMのストレージを別の場所に移行した場合、移行前に作成されたバックアップコピーからそのVMにリストアすることはできません。
* Windows Server 2012では、バックアップセットにCluster Shared Volume（CSV；クラスタ共有ボリューム）と共有ディスクの両方が含まれている場合、バックアップジョブを実行できません。
* ストレージ接続の管理設定では、リモート手順 コール（RPC）プロトコルは使用できません。使用できるプロトコルはHTTPプロトコルとHTTPSプロトコルのみです。
* NASストレージに格納された仮想マシン（VM）について、アプリケーションと整合性のあるバックアップを作成することは、Windows Server 2012 Hyper-Vオペレーティングシステムではサポートされていません。
+
この制限は、crash-consistentバックアップには適用されません。ファイル共有のシャドウコピーサービスは含まれない、空きHyper-Vサーバは環境 だけになります。

* VMの仮想スイッチ名は、プライマリWindowsホストとセカンダリWindowsホストでまったく同じにする必要があります。
* Hyper-V VMをSMB 3.0経由で導入する場合は、バックアップとリストアの処理にFlexCloneライセンスが必要です。
* リストア処理でサポートされるLUNの最大サイズは14TBです。
* 次のHyper-Vサーバでは、アプリケーションと整合性のあるVMのバックアップはサポートされていません。
+
** Microsoft Hyper-V Server 2016（無償版）
** Microsoft Hyper-V Server 2019（無償版）この制限は、crash-consistentバックアップまたは次のWindowsプラットフォームには適用されないことに注意してください。
** Microsoft Windows Server 2016 Standard EditionおよびDatacenter Edition
** Microsoft Windows Server 2019 Standard EditionおよびDatacenter Edition



