---
permalink: concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html 
sidebar: sidebar 
keywords: create, monitor, on-demand, backup, manage, schedule, snapmanager, hyper-v, creating, managing, application, crash 
summary: SnapManager for Hyper-Vでは、オンデマンドバックアップやスケジュールされた管理バックアップを作成して監視することができます 
---
= SnapManager for Hyper-Vでバックアップジョブを作成して管理する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-Vでは、オンデマンドバックアップやスケジュールされた管理バックアップを作成して監視することができますまた、SnapManager for Hyper-Vでは、アプリケーション整合性とクラッシュ整合性の2種類のバックアップジョブを実行することもできます。



== SnapManager for Hyper-Vのバックアップについて

オンデマンドバックアップジョブを作成して必要なときに実行したり、データセットに関連付けられたポリシーを使用してスケジュール設定されたバックアップジョブを作成したりできます。オンデマンドバックアップジョブには、保持ポリシーとレプリケーションポリシー、およびバックアップの前後に実行するスクリプトを含めることができます。スケジュール済みバックアップジョブを構成するポリシーを作成、変更、表示、および削除できます。



== SnapManager for Hyper-Vで実行できるバックアップジョブのタイプ

SnapManager for Hyper-Vでは、アプリケーション整合性とクラッシュ整合性の2種類のバックアップジョブを実行できます。



== アプリケーションと整合性のあるバックアップジョブ

アプリケーションと整合性のあるバックアップジョブは、徹底的で信頼性が高く、大量のリソースを必要とします。Snapshotコピーは、MicrosoftのVolume Shadow Copy Service（VSS；ボリュームシャドウコピーサービス）と連携して、VMで実行されている各アプリケーションを休止してからSnapshotコピーを作成します。このバックアップ方式では、アプリケーションデータの整合性が保証されます。このサーバを使用して、VMおよびVM上で実行されているアプリケーションをリストアできます。ただし、アプリケーションと整合性のあるバックアップジョブは時間がかかり、複雑になりがちです。



== crash-consistentバックアップジョブ

crash-consistentバックアップジョブは、データセットに含まれるVMで使用されるすべてのLUNのSnapshotコピーです。作成されるバックアップコピーは、クラッシュまたは突然電源がオフになるVMのデータキャプチャと似ています。crash-consistentバックアップジョブはデータを迅速にキャプチャする手段を提供しますが、crash-consistentバックアップからリストアするにはVMが存在している必要があります。crash-consistentバックアップジョブは、アプリケーションと整合性のあるバックアップジョブの代わりに使用するものではありません。



== SnapManager for Hyper-Vのバックアップ要件と制限事項

SnapManager for Hyper-Vのバックアップの要件と制限事項を理解しておく必要があります。

* MetroCluster 構成でスイッチオーバーまたはスイッチバック処理を実行する場合は、バックアップとリストアの処理がサポートされません。バックアップおよびリストア処理とスイッチオーバーまたはスイッチバック処理が同時に実行されている場合、Windows Server 2012 R2システムでは、VMの「.vhd」ファイル形式が「.avhdx」に変更される可能性があります。VMはこの変更の影響を受けません。
* 分散型のアプリケーション・コンシステント・バックアップ・オプションを使用すると'パートナー・クラスタ・ノード上で実行されている複数のVMが'バックアップ・ノードから作成された1つのハードウェアSnapshotコピー内で一貫性を保つことができますこのオプションは、Windowsフェイルオーバークラスタの複数のノードにまたがるCSV 2.0 Windowsボリュームで実行されているすべてのVMでサポートされます。
* 7-Modeでは、アプリケーションと整合性のあるバックアップジョブがVSS Hardware Providerを使用して、2つのSnapshotコピーを作成します。Snapshotコピーは'snapshot_name'および'snapshot_name_backup'と呼ばれますこの2つのSnapshotコピーが作成されるので、VSSバックアップ中に自動でリカバリできます。
* クラスタ環境では、アプリケーションと整合性のあるバックアップに必要なSnapshotコピーは、自動リカバリプロセス用に1つだけです。SISクローンは自動リカバリの実行に活用され'自動リカバリが完了すると'最初のSnapshotコピー(snapshot_name')が削除されます
* VM内の各Windowsボリュームに300MB以上の空きディスクスペースが必要です。これには、VMに接続されているVHD、iSCSI LUN、パススルーディスクに対応するWindowsボリュームが含まれます。
* crash-consistentバックアップジョブでは、常にSnapshotコピーが1つだけ作成されます。VSSとの統合は行われません。
* crash-consistentバックアップジョブは、複数同時に実行できます。crash-consistentバックアップジョブは、アプリケーションと整合性のあるバックアップジョブと並行して実行できます。
* 「保存された状態のバックアップを許可」は、クラッシュ整合性のあるバックアップ・ジョブには適用されません。

