---
settings:
  name: SnapManager for Hyper-V
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: SnapManager for Hyper-Vのドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/release-notes.html"
  - title: SnapManager for Hyper-Vとは
    url: "/concept-what-snapmanager-for-hyper-v-is.html"
    entries:
    - title: SnapManager for Hyper-Vの機能
      url: "/concept-what-you-can-do-with-snapmanager-for-hyper-v.html"
    - title: SnapManager for Hyper-Vの制限事項の一覧です
      url: "/concept-snapmanager-for-hyper-v-limitations.html"
    - title: データ管理の概念
      url: "/concept-data-management-concepts.html"
  - title: SnapManager for Hyper-Vをインストールするための要件の一覧です
    url: "/reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html"
    entries:
    - title: SnapManager for Hyper-VのONTAP ライセンス
      url: "/reference-snapmanager-for-hyper-v-licensing-for-ontap.html"
    - title: Hyper-V親ホストの要件
      url: "/reference-hyper-v-parent-host-requirements.html"
    - title: Windows Server環境用の修正プログラムの要件
      url: "/reference-hotfix-requirements-for-windows-server-environments.html"
    - title: ライセンス要件
      url: "/reference-license-requirements.html"
    - title: リモートホストインストールウィザードを使用するための要件
      url: "/reference-requirements-for-remote-host-install.html"
  - title: SnapManager for Hyper-Vをインストールします
    url: "/concept-install-snapmanager-for-hyper-v.html"
    entries:
    - title: SnapManager for Hyper-Vをダウンロードします
      url: "/task-download-snapmanager-for-hyper-v.html"
    - title: SnapDrive for WindowsおよびSnapManager for Hyper-Vのインストール順序
      url: "/concept-installation-order-for-snapdrive-for-windows-and-snapmanager-for-hyper-v.html"
    - title: SnapManager for Hyper-Vをインストールします
      url: "/task-install-snapmanager-for-hyper-v.html"
    - title: ノードまたはホストにSnapManager for Hyper-Vをリモートでインストールまたはアンインストールする
      url: "/task-remotely-install-or-uninstall-snapmanager-for-hyper-v-on-nodes.html"
    - title: サイレントインストール用のコマンドラインスイッチのリストと概要
      url: "/reference-command-line-switch-descriptions.html"
  - title: WindowsでSnapManager for Hyper-Vをアンインストールします
    url: "/concept-uninstall-snapmanager-for-hyper-v-on-windows.html"
    entries:
    - title: SnapManager for Hyper-Vをアンインストールします
      url: "/task-uninstall-snapmanager-for-hyper-v.html"
  - title: Hyper-V用にSnapManager を設定します
    url: "/concept-configure-snapmanager-for-hyper-v.html"
    entries:
    - title: ダッシュボードの設定
      url: "/concept-dashboard-settings.html"
    - title: ホストを設定
      url: "/concept-configure-hosts.html"
      entries:
      - title: Hyper-V親ホストまたはホストクラスタを追加する場合の要件
        url: "/reference-requirements-for-adding-a-hyper-v-parent-host-or-host-cluster.html"
      - title: Hyper-V親ホストまたはホストクラスタを追加
        url: "/task-add-a-hyper-v-parent-host-or-host-cluster.html"
      - title: ストレージ接続の設定を管理します
        url: "/task-manage-storage-connection-settings.html"
      - title: Hyper-V親ホストまたはホストクラスタを表示する
        url: "/task-view-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 仮想マシンを表示します
        url: "/task-view-a-virtual-machine.html"
      - title: Hyper-V操作用にSnapManager 用のHyper-V仮想マシンを移行する
        url: "/task-migrate-a-hyper-v-virtual-machine-to-support-snapmanager-for-hyper-v-operations.html"
      - title: ホストとデータセットの設定情報をインポートまたはエクスポートします
        url: "/task-import-or-export-host-and-dataset-configuration-information.html"
      - title: Hyper-V親ホストまたは親ホストクラスタを削除
        url: "/task-remove-a-hyper-v-parent-host.html"
      - title: イベント通知設定
        url: "/concept-event-notification-settings.html"
        entries:
        - title: E メール通知を設定
          url: "/concept-configure-multiple-recipients-for-email-notifications-in-smhv.html"
      - title: レポートパスの設定
        url: "/concept-report-path-settings.html"
    - title: SnapInfoディレクトリを設定します
      url: "/concept-configure-snapinfo-directory-settings.html"
      entries:
      - title: SnapInfo LUNをセットアップします
        url: "/task-set-up-a-snapinfo-lun.html"
      - title: SnapInfoディレクトリパスを変更します
        url: "/task-change-the-snapinfo-directory-path.html"
    - title: データセットを設定する
      url: "/concept-configure-datasets.html"
      entries:
      - title: データセットの作成要件
        url: "/reference-requirements-for-creating-a-dataset.html"
      - title: データセットを作成します
        url: "/task-create-a-dataset.html"
      - title: データセットを変更する
        url: "/task-modify-a-dataset.html"
      - title: データセットを表示します
        url: "/task-view-a-dataset.html"
      - title: データセットを削除する
        url: "/task-delete-a-dataset.html"
    - title: ポリシーを設定する
      url: "/concept-configure-policies.html"
      entries:
      - title: データセットにポリシーを追加するための要件
        url: "/reference-requirements-for-adding-policies-to-a-dataset.html"
      - title: ポリシーを追加します
        url: "/task-add-policies.html"
      - title: ポリシーを変更する
        url: "/task-modify-policies.html"
      - title: ポリシーを表示します
        url: "/task-view-policies.html"
      - title: ポリシーを削除する
        url: "/task-delete-policies.html"
    - title: Hyper-V over SMB用のSVMまたはCIFSサーバを設定
      url: "/concept-configure-svms-or-cifs-servers-for-hyper-v-over-smb.html"
  - title: レポートの管理
    url: "/concept-report-management.html"
    entries:
    - title: データセット・レポートを表示する
      url: "/task-view-a-report.html"
    - title: ホストレポートを表示します
      url: "/task-view-a-host-report.html"
    - title: レポートを削除します
      url: "/task-delete-a-report.html"
  - title: VSSコンポーネント
    url: "/concept-overview-of-vss-components.html"
    entries:
    - title: Windows Server 2012以降のCSV 2.0
      url: "/concept-cluster-shared-volume-2-0-architecture.html"
    - title: SMB 3.0は、Windows Server 2012のHyper-V VMをサポートします
      url: "/reference-smb-3-0-support-hyper-v-vms-in-windows-server-2012.html"
    - title: SnapManager for Hyper-VでのVSSの使用方法
      url: "/concept-how-snapmanager-for-hyper-v-uses-vss.html"
    - title: ONTAP VSS Hardware Providerの要件
      url: "/concept-ontap-vss-hardware-provider-requirement.html"
    - title: インストール済みのVSSプロバイダを表示します
      url: "/task-view-installed-vss-providers.html"
    - title: VSSハードウェアプロバイダが正常に使用されたことを確認します
      url: "/task-verify-that-the-vss-hardware-provider-was-used-successfully.html"
  - title: SnapManager for Hyper-Vでバックアップジョブを作成して管理する
    url: "/concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html"
    entries:
    - title: データセットを手動でバックアップするための要件
      url: "/reference-requirements-for-manually-backing-up-a-dataset.html"
    - title: SnapManager for Hyper-Vによる保存状態のバックアップの処理方法
      url: "/concept-how-snapmanager-for-hyper-v-handles-saved-state-backups.html"
    - title: データセットの手動バックアップ
      url: "/task-manually-backing-up-a-dataset.html"
    - title: バックアップジョブを監視する
      url: "/task-monitor-backup-jobs.html"
    - title: バックアップを削除します
      url: "/task-delete-a-backup.html"
  - title: バックアップコピーから仮想マシンをリストアする
    url: "/concept-restore-a-virtual-machine.html"
    entries:
    - title: 仮想マシンをリストアするための要件
      url: "/reference-requirements-for-restoring-a-virtual-machine.html"
    - title: バックアップコピーから仮想マシンをリストアする
      url: "/task-restore-a-virtual-machine-from-a-backup-copy.html"
  - title: クラスタオペレーティングシステムのローリングアップグレードを実行する
    url: "/concept-perform-a-cluster-os-rolling-upgrade.html"
    entries:
    - title: LUNをオペレーティングシステムが混在したモードでマッピングします
      url: "/task-map-luns-after-the-windows-server-2016-node-addition.html"
    - title: すべてのノードでデータセットとSnapInfoを更新します
      url: "/task-update-the-dataset-and-snapinfo-across-all-nodes.html"
  - title: ディザスタリカバリを実行
    url: "/concept-perform-disaster-recovery.html"
    entries:
    - title: フェイルオーバー用にSnapManager を設定します
      url: "/concept-configure-snapmanager-for-hyper-v-for-failover.html"
    - title: ディザスタリカバリフェイルオーバーからリカバリと再実行を行います
      url: "/task-recover-and-restore-from-a-disaster-recovery-failover.html"
    - title: ディザスタリカバリフェイルバック後にストレージシステムを再設定する
      url: "/task-reconfigure-storage-systems-after-a-disaster-recovery-failback.html"
    - title: スタンドアロンホストの元の構成をリストアします
      url: "/task-restore-the-original-configuration-for-standalone-hosts.html"
    - title: クラスタホストの元の構成をリストアします
      url: "/task-restore-the-original-configuration-for-clustered-hosts.html"
  - title: SnapManager for Hyper-Vのトラブルシューティングを実行します
    url: "/concept-snapmanager-for-hyper-v-troubleshoot.html"
    entries:
    - title: 次のVMはオンラインでバックアップできないか、バックアップ対象としてVMが見つかりません
      url: "/reference-backup-failed-for-the-following-vm-s-since-it-cannot-be-backedup-online-or-no-vm-to-be-found-for-backup.html"
    - title: IVssWriterCallbackインターフェイスの照会中に予期しないエラーが発生しました。HR = 0x80070005、Access
        is denied（アクセスが拒否されました）。
      url: "/reference-unexpected-error-querying-for-the-ivsswritercallback-interface-hr-0x80070005.html"
    - title: バックアップレポートでは、レポート名に管理コンソールのタイムゾーン情報が使用されます
      url: "/reference-backup-reports-use-management-console-time-zone-information-in-report-name.html"
    - title: バックアップとリストアの通知は、IPv6のみの環境では送信されません
      url: "/reference-backup-and-restore-notifications-not-sent-in-ipv6-only-environments.html"
    - title: フェイルオーバークラスタリングイベントID 5121
      url: "/reference-failover-clustering-event-id-5121.html"
    - title: リストア処理の実行中に作成された仮想マシンのバックアップが無効になる可能性があります
      url: "/reference-virtual-machine-backups-made-while-a-restore-operation-is-in-progress-might-be-invalid.html"
    - title: 自身を管理する仮想マシン
      url: "/reference-virtual-machine-adding-itself-to-a-dataset.html"
    - title: IPv6専用ホストでは接続時間が長くなります
      url: "/reference-connection-time-is-longer-with-ipv6-only-host.html"
    - title: ボリュームシャドウコピーサービスのエラー：内部の不整合が検出されました
      url: "/reference-volume-shadow-copy-service-error-an-internal-inconsistency-was-detected.html"
    - title: Webサービスクライアントチャネルがマシンsmhv51_81clus上のConfigurationManagementServiceインスタンスに接続できませんでした
      url: "/reference-web-service-client-channel-was-unable-to-connect-to-the-configurationmanagementservice-instance-on-machine-smhv51-81clus.html"
    - title: サイレントインストールで使用されるMSIカスタムプロパティ
      url: "/reference-msi-custom-property-used-in-silent-installation.html"
    - title: ホストまたはストレージシステムにSnapManager for Hyper-Vのライセンスがありません
      url: "/reference-snapmanager-for-hyper-v-is-not-licensed-on-the-host-or-in-the-storage-system.html"
    - title: フェイルオーバー後にバックアップを削除する
      url: "/reference-secondary-machine-unable-to-delete-backups-after-failover.html"
    - title: バックアップが失敗すると、ストレージパフォーマンスが低下します
      url: "/reference-storage-performance-degrades-after-failed-backup.html"
    - title: SnapInfoのSnapshotコピーが削除されました
      url: "/reference-retention-of-snapinfo-snapshot-copies.html"
    - title: アンチウイルス解決策 によるメモリ消費量が多い
      url: "/reference-high-memory-consumption-caused-by-antivirus-solution.html"
    - title: バックアップごとに2つのSnapshotコピーを作成するときのスペース消費
      url: "/reference-space-consumption-when-making-two-snapshot-copies-for-each-backup.html"
    - title: SnapDrive SDDiscoveryFileSystemListInfo応答は、バックアップ中にNULLになります
      url: "/reference-error-snapdrive-sddiscoveryfilesystemlistinfo-response-is-null.html"
    - title: エラー：VSSリクエスタ-バックアップコンポーネントが失敗しました
      url: "/reference-error-vss-requestor-backup-components-failed.html"
    - title: VSSリクエスタ-バックアップコンポーネントに失敗しました。想定されたディスクがシステムに到着しませんでした
      url: "/reference-error-vss-requestor-backup-components-failed-an-expected-disk-did-not-arrive-in-the-system.html"
    - title: VSSリクエスタ-ライターの一部エラーによりコンポーネントをバックアップできませんでした
      url: "/reference-dataset-backup-might-fail-with-a-partial-writer-error.html"
    - title: VSSは、NASバックアップ中にMicrosoft iSCSI Target VSS Hardware Providerに対するエラーを返します
      url: "/reference-vss-returns-errors-against-microsoft-iscsi-target-vss-hardware-provider-during-nas-backup.html"
    - title: VSSリクエスタ-バックアップコンポーネントに失敗しました。Snapshotセットの保持の呼び出しに失敗しました。
      url: "/reference-vss-requestor-backup-components-failed-failed-to-call-keep-snapshot-set.html"
    - title: Hyper-VのSnapManager ではMBR LUNはサポートされません
      url: "/reference-mbr-luns-unsupported-in-snapmanager-for-hyper-v.html"
    - title: Hyper-V Managerから仮想マシンを削除すると、バックアップが失敗する
      url: "/reference-backup-fails-after-removing-virtual-machine-from-hyper-v-manager.html"
    - title: 一部のタイプのバックアップが失敗しても、パーシャル・バックアップに失敗することはありません
      url: "/reference-some-types-of-failures-do-not-generate-error-message.html"
    - title: ストレージシステムボリューム名の変更後にリストアに失敗しました
      url: "/reference-restore-failure-after-storage-system-volume-renaming.html"
    - title: フェイルバック後にバックアップからリストアする
      url: "/reference-restore-from-a-backup-after-failback.html"
    - title: データセットを新しいノードに更新中は、Web Service Clientチャネルに接続できません
      url: "/reference-web-service-client-channel-unable-to-connect-while-updating-the-dataset-to-the-new-node.html"
    - title: Windowsフェイルオーバークラスタ内の新しいノードには、データセットが自動的にレプリケートされません
      url: "/reference-datasets-are-not-automatically-replicated-to-new-nodes-in-a-windows-failover-cluster.html"
    - title: エラー1935。アセンブリ構成部品のインストール中にエラーが発生しました
      url: "/reference-error-1935-an-error-occurred-during-the-installation-of-assembly-component.html"
    - title: 同じストレージシステムのCSVが15個を超えると、バックアップジョブが失敗する可能性があります
      url: "/reference-backup-jobs-that-involve-more-than-15-csvs-from-the-same-filer-fail-with-rename-snapshot-error.html"
    - title: 指定したVMが存在しないか、オンラインでバックアップできません
      url: "/reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html"
    - title: 必要な修正プログラムのKB2263829は、一部のプラットフォームにインストールできません
      url: "/reference-required-hotfix-kb2263829-cannot-be-installed-on-some-platforms.html"
    - title: "「シャドウコピーの作成はすでに実行中です」というエラーが表示されてバックアップに失敗しました。"
      url: "/reference-backup-fail-with-the-error-shadow-copy-creation-is-already-in-progress.html"
  - title: 法的通知
    url: "/legal-notices.html"
