---
permalink: reference-requirements-for-restoring-a-virtual-machine.html 
sidebar: sidebar 
keywords: restore, virtual, machine, backup, copy, requirement 
summary: バックアップコピーから仮想マシンをリストアするには、まずバックアップコピーのリストア方法を決定する必要があります。 
---
= 仮想マシンをリストアするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
バックアップコピーから仮想マシンをリストアするには、まずバックアップコピーのリストア方法を決定する必要があります。



== VMバックアップコピーの名前

リストアするバックアップコピーを決定する必要があります。

すべてのバックアップコピーは、Recovery ManagementウィンドウのBackupsペインに名前で表示されます。



== VMバックアップコピータイプ

アプリケーションと整合性のあるバックアップからVMをリストアする処理は、VSSと連携して行います。Hyper-V VSSライターは、リストア処理の完了後にVMをリストアしてHyper-V Managerに登録する前に、そのVMを削除します。

crash-consistentバックアップからVMをリストアする場合、VSSは使用しません。リストア処理の前にVMの電源がオフになります。crash-consistentバックアップからリストアする場合は、VMが存在している必要があります。crash-consistentバックアップから削除されたVMをリストアすると失敗します。



== VMバックアップコピーのステータス

仮想マシンがまだ存在するかどうかを確認する必要があります。

仮想マシンが存在しなくなっても、その仮想マシンが作成されたLUNが残っていればリストアできます。LUNのドライブレターとWindowsボリュームGUIDは、バックアップ時と同じである必要があります。

Windows Server 2008 R2で仮想マシンを削除すると、アプリケーションと整合性のあるバックアップからその仮想マシンをリストアできますが、Windows Server 2012およびWindows Server 2012 R2では、クラッシュとアプリケーションと整合性のあるバックアップの両方から、削除した仮想マシンをリストアできます。

仮想マシンが削除される前にすべてのデータセットから削除された場合でも、[保護されていないリソース]を選択して、その仮想マシンが属していたバックアップを選択することにより、仮想マシンをリストアできます。



== VMバックアップコピーの設定ステータス

仮想マシンの設定がバックアップ時と同じかどうかを確認する必要があります。

現在の仮想マシン構成がバックアップ時点と異なる場合、仮想マシンのレイアウトが変更されたことを示すSnapManager for Hyper-Vから、バックアップに存在した仮想マシンの構成とデータをリストアするかどうかを確認するメッセージが表示されます。


NOTE: SnapManager for Hyper-Vは仮想マシンのクラスタ構成をバックアップしないため、クラスタ構成をリストアできません。仮想マシンとクラスタの構成が失われた場合、SnapManager for Hyper-Vから仮想マシンをリストアできますが、その場合は手動でハイアベイラビリティを構成する必要があります。

仮想マシンの設定がバックアップ内の仮想マシンの現在の構成と異なる場合は、新たに追加または削除されたVirtual Hard Disk（VHD；仮想ハードディスク）を反映するために、クラスタ構成の更新が必要になることがあります。



== Snapshotコピーのステータス

リストア処理を開始する前に、バックアップSnapshotコピーがストレージシステムに存在しているかどうかを確認できます。



== VMが再起動します

リストア後に仮想マシンを起動するように選択できます。

* 関連情報 *

http://technet.microsoft.com/library/ff182338(v=WS.10).aspx["Microsoft TechNet：「Windows Server 2008 R2のフェイルオーバークラスタ"]
