---
permalink: reference_requirements_for_adding_a_hyper_v_parent_host_or_host_cluster.html 
sidebar: sidebar 
keywords: configuration, information, available, parent, host, cluster, snapmanager, hyper-v 
summary: SnapManager for Hyper-Vに親ホストまたはホストクラスタを追加する前に、必要な設定情報がすべて揃っている必要があります 
---
= Hyper-V親ホストまたはホストクラスタを追加する場合の要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-Vに親ホストまたはホストクラスタを追加する前に、必要な設定情報がすべて揃っている必要があります



== SnapManager for Hyper-Vのインストール

追加するHyper-VホストにSnapManager for Hyper-Vがインストールされている必要があります。

Hyper-V用のSnapManager がインストールされていない場合は、リモートホストインストールウィザードを実行するように求められます。各クラスタノードには、同じバージョンのHyper-V用SnapManager をインストールする必要があります。



== 構成設定

追加するHyper-V親ホストがHyper-VのSnapManager 用に設定されている必要があります

SnapManager for Hyper-Vに対してSnapInfoの設定、レポートディレクトリの設定、通知の設定が行われていない場合は、ホストの追加後に設定ウィザードを使用して設定できます。

最初は、[ストレージ接続の管理]タブが空です。ストレージ接続は、「*ストレージ接続の管理」タブから追加できますが、新しく追加した接続は、SnapDrive for Windows（SDW）のトランスポートプロトコル設定（TPS）で確認できます。

SnapManager for Hyper-Vを使用して仮想マシンを追加および管理するには、バックアップリポジトリとレポートディレクトリを設定する必要があります通知設定はオプションです。



== 仮想マシンとONTAP LUN

構成ファイル、Snapshotコピーのファイルの場所、VHDなど、仮想マシンに関連付けられたすべてのファイルは、ONTAP LUN上に存在する必要があります。

この手順は、バックアップを正常に実行するために必要です。


NOTE: 仮想マシンの作成後に仮想マシンのSnapshotファイルの場所を別のONTAP LUNに変更した場合は、Hyper-Vマネージャを使用して仮想マシンのSnapshotコピーを少なくとも1つ作成してから、SnapManager for Hyper-Vを使用してバックアップを作成してくださいSnapshotコピーファイルの場所を変更した場合、バックアップを作成する前に仮想マシンのSnapshotコピーを作成しないと、バックアップ処理が失敗することがあります。



== 専用およびクラスタ化された仮想マシン

仮想マシンは、専用またはクラスタの一部として使用できます。

ホストを1つ追加すると、そのホストの専用仮想マシンはSnapManager for Hyper-Vによって管理されます。ホストクラスタを追加すると、SnapManager for Hyper-Vはホストクラスタ上の共有仮想マシンを管理します。SANおよびNAS上の同じホストクラスタに属する仮想マシンは、同じデータセット内に存在しないようにする必要があります。これらのタイプ原因 のリソースを単一のデータセットに追加すると、データセットのバックアップが失敗する可能性があります。

アプリケーションと整合性のあるバックアップでは、クラスタ化された仮想マシンをクラスタの別のノードで実行する場合、クラスタ化された仮想マシンのデータセットバックアップの完了に時間がかかります。仮想マシンを異なるノード上で実行する場合は、クラスタ内のノードごとに個別のバックアップ処理が必要です。すべての仮想マシンを同じノードで実行する場合は、バックアップ処理が1回だけで済み、バックアップにかかる時間が短縮されます。



== 仮想マシンの数

Hyper-Vホストまたはホストクラスタに1、000台を超える仮想マシンがある場合は、Hyper-Vキャッシュマネージャ用のSnapMgrServiceHost.exe.configファイルで、maximElementsInCacheBeforeScavengingプロパティの値を増やす必要があります。この値は、スタンドアロンのホストまたはクラスタで実行されているHyper-Vホストの数以上にする必要があります。クラスタの各ノードの値を変更してから、この値を変更したあとにSnapManager for Hyper-Vサービスを再起動する必要があります。SnapMgrServiceHost.exe.configファイルをテキストエディタを使用して手動で編集する必要があります。

[listing]
----
<cacheManagers>
…
      <add name="HyperV Cache Manager"
                        type="Microsoft.Practices.EnterpriseLibrary.Caching.CacheManager,
                           Microsoft.Practices.EnterpriseLibrary.Caching"
                        expirationPollFrequencyInSeconds="60"
                        maximumElementsInCacheBeforeScavenging="1200"
                        numberToRemoveWhenScavenging="10"
                        backingStoreName="inMemory" />
…
</cacheManagers>
----


== SnapManager for Hyper-Vのサービスアカウントの要件

SnapManager for Hyper-Vを使用してHyper-Vホストクラスタを管理する場合、Hyper-VおよびSnapDrive for WindowsのサービスアカウントのSnapManager は、サーバに対するローカル管理者権限を持つドメインユーザアカウントである必要があります。

SnapManager for Hyper-Vアプリケーションと整合性のあるバックアップは、仮想マシンが実行されているクラスタノードで実行されます。仮想マシンが使用するクラスタ共有ボリューム（CSV）が同じノードに所有されていないと、SnapManager for Hyper-Vサービスがローカルシステムアカウントを使用している場合（アカウントに管理者権限がある場合でも）仮想マシンのバックアップが失敗することがあります。この場合、SnapManager for Hyper-Vは、仮想マシンファイルがCSV上にあることを検出できないため、バックアップは失敗します。


NOTE: clustered Data ONTAP のSMB 3.0の継続的可用性（CA）共有に格納された仮想マシンを使用したリモートのVolume Shadow Copy Service（VSS；ボリュームシャドウコピーサービス）処理が正常に機能するためには、 SnapDrive for Windowsサービスアカウントには、共有に対するフルコントロール権限を付与し、SnapManager for Hyper-V Webサービスアカウントへの最小限の読み取りレベルアクセスを付与する必要があります。

* 関連情報 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：「Hyper-V」"]
