---
permalink: reference-requirements-for-manually-backing-up-a-dataset.html 
sidebar: sidebar 
keywords: backup, dataset, manual, first, name, describe, type, option, retention, policy, requirement 
summary: データセットを手動でバックアップするには、まずデータセット名と説明を入力し、バックアップのタイプとオプションを選択して、保持ポリシーを設定する必要があります。 
---
= データセットを手動でバックアップするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データセットを手動でバックアップするには、まずデータセット名と説明を入力し、バックアップのタイプとオプションを選択して、保持ポリシーを設定する必要があります。



== バックアップ名と概要

バックアップには名前と概要 を割り当てる必要があります。

バックアップのデフォルトの命名規則はDatasetName_Timestampです。バックアップ名には、タイムスタンプ以外のすべての情報を変更できます。タイムスタンプは常にバックアップ名の一部として表示されます。

バックアップの名前と説明に使用できる文字は次のとおりです。

* a ~ z
* A ~ Z
* 0～9
* _（アンダースコア）
* -（ハイフン）




== ポリシーの選択

オンデマンドバックアップに使用するポリシーを決定する必要があります。

バックアップウィザードでは、特定のポリシーを選択できます。ポリシー自体を変更することなく、保持ポリシーやレプリケーションポリシー、ポリシーに関連付けられているスクリプトを上書きすることができます。

なしを選択すると、ポリシーを作成せずにオンデマンドバックアップを作成することもできます。このオプションでは、保持ポリシー、レプリケーションポリシー、およびスクリプトのデフォルト値が使用されます。



== 保持値

選択したポリシーで指定されている保持ポリシーを上書きすることもできます。この場合には、バックアップコピーを削除する前に、毎時、毎日、毎週、毎月、または無制限に保持する期間の最小値を決定する必要があります。

バックアップは、時間または指定した数に基づいて保持できます。たとえば、最新のバックアップを10個保持したり、15日を超過した古いバックアップを削除したりできます。



== バックアップのタイプ

アプリケーションと整合性のあるバックアップとcrash-consistentバックアップを実行できます。



== バックアップオプション

保存された状態のバックアップを許可できます。

Hyper-V用SnapManager のデフォルトの動作では、1つ以上の仮想マシンをオンラインバックアップできない場合、バックアップは失敗します。仮想マシンが保存された状態にあるか、シャットダウンされている場合は、オンラインバックアップを実行できません。状況によっては、仮想マシンが保存された状態にあるか、メンテナンスのためにシャットダウンされている場合もありますが、オンラインバックアップができない場合でも、バックアップを続行する必要があります。これを行うには、保存された状態の仮想マシンを移動するか、保存された状態のバックアップを許可するポリシーが設定された別のデータセットにシャットダウンします。

また、Allow saved state VM backupチェックボックスを選択して既存のポリシーを変更することもできます。これにより、保存された状態の仮想マシンをSnapManager for Hyper-Vがバックアップできるようになります。このオプションを選択した場合、Hyper-V VSSライターが保存された状態の仮想マシンをバックアップしたり、仮想マシンのオフラインバックアップを実行したりしても、SnapManager for Hyper-Vはバックアップを失敗させません。保存された状態またはオフラインのバックアップを実行すると、原因 が停止する可能性があります

分散型のアプリケーション・コンシステント・バックアップ機能を使用すると'パートナー・クラスタ・ノード上で実行されている複数のVMの整合性を'バックアップ・ノードから作成された1つのハードウェアSnapshotコピーで確保できますこの機能は、Windowsフェイルオーバークラスタの複数のノードにまたがるCSV 2.0 Windowsボリュームで実行されているすべてのVMでサポートされます。



== SnapMirrorバックアップのセカンダリストレージ

これらのオプションを使用すると、SnapMirror関係に定義されているセカンダリストレージに適用可能なオプションを指定できます。「* Update SnapMirror after backup *」を選択できます。[ボールトラベルオプション（Vault label option）]パネルで、[バックアップ後にSnapVault を更新（Update after backup）]を選択できます。*バックアップ後にSnapVault を更新*を選択した場合は、ドロップダウンメニューからボルトラベルを選択するか、カスタムラベルを入力する必要があります。



== バックアップスクリプト

選択したポリシーに指定されているスクリプトオプションは無効にすることができます。

これらのスクリプトは、スクリプトで特定のホストを指定しないかぎり、すべてのデータセットメンバーホスト上で実行されます。

* 関連情報 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：「Hyper-V」"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html["ONTAP 9 SnapVault によるボリュームバックアップエクスプレスガイド"]
