---
permalink: reference-license-requirements.html 
sidebar: sidebar 
keywords: run, snapmanager, hyper-v, select, host-based, storage, system, license, installation, license 
summary: SnapManager for Hyper-Vを実行するには、ライセンスのインストール時にホストベースまたはストレージシステムのいずれかのライセンスを選択する必要があります。 
---
= ライセンス要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-Vを実行するには、ライセンスのインストール時にホストベースまたはストレージシステムのいずれかのライセンスを選択する必要があります。



== SnapManager スイートライセンス

WindowsホストシステムにはSnapManager スイートライセンスが必要です。ホストベースのライセンスまたはストレージシステム単位のライセンスを選択できます。



== サーバ単位のライセンス

これは、_ホストベースのライセンス_とも呼ばれます。ホストベースのライセンスを選択した場合は、インストール時にSnapManager スイートのライセンスキーを指定する必要があります。このライセンスキーは、必要に応じてあとから変更できます。インストール後にライセンスキーを変更するには、SnapManager for Hyper-V Welcome（Hyper-Vようこそ）ウィンドウで* License settings（ライセンス設定）*をクリックします。各親ホストにはSnapManager スイートライセンスが必要です。



== ストレージシステム単位ライセンス

これは、_storage system licensing_.と呼ばれます。ストレージシステム単位のライセンスを選択した場合、SnapManager for Hyper-Vの処理を実行するには、すべてのストレージシステムにSnapManager スイートライセンスを追加する必要があります。



== クライアントシステム単位のライセンスです

管理コンソールをインストールする場合は、このライセンスオプションを使用してください。
