---
permalink: reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html 
sidebar: sidebar 
keywords: vm, present, backed, up, online 
summary: 指定したVMが存在しないか、オンラインでバックアップできません 
---
= 指定したVMが存在しないか、オンラインでバックアップできません
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* * メッセージ *
+
'指定されたVMが存在しないか'オンラインでバックアップできません

* * 概要 *
+
このメッセージが表示されるのは、VMのパススルーディスクのサイズが300MB未満の場合に、アプリケーションと整合性のあるバックアップが失敗したときです。エラーログは次の例のようになります。

+
[listing]
----
Log Name:      Application
Source:        SnapMgrServiceHost
Date:          11/12/2012 12:24:28 PM
Event ID:      106
Task Category: Backup Event
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      defiant16.wak-qa.com
Description:
SnapManager for Hyper-V backup failed to complete

Backup Failed for the following VM(s) since it cannot be backedup online or No VM to be found for backup
               VM Name: demovm-0
----
+
障害を示す他のアプリケーションまたはシステムエラーメッセージはありません。

* * 是正措置 *
+
パススルーディスクのサイズは300 MBを超えるように変更するか、Allow Saved state VM backupオプションを有効にしてバックアップを実行できます。

+

NOTE: この対処方法は、SAN環境とNAS環境の両方に該当します。

* * メッセージ *
+
'指定されたVMが存在しないか'オンラインでバックアップできません

* * 概要 *
+
このメッセージが表示される2つ目の理由は、Hyper-V VMに対して対象となるSnapshotオプションが有効になっているために、Windowsがこのシステムのオンラインバックアップを実行できないことです。スコープ付きスナップショットは、主にWindowsの重要な更新プログラムで使用されます。

* * 是正措置 *
+
スコープ・スナップショット・オプションを無効にするには'0のDWORD ScopeSnapshot'パラメータを作成します

+
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\SystemRestore\`

+

NOTE: この対処方法は、SAN環境とNAS環境の両方に該当します。


