---
permalink: reference_hyper_v_parent_host_requirements.html 
sidebar: sidebar 
keywords: hyper-v, parent, host, physical, server, enable, contain, virtual, machine, snapmanager, requirement 
summary: Hyper-V親ホストは、Hyper-Vの役割が有効になっている物理サーバです。 
---
= Hyper-V親ホストの要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Hyper-V親ホストは、Hyper-Vの役割が有効になっている物理サーバです。仮想マシンを格納するホストサーバは、保護とリカバリのためにSnapManager for Hyper-Vに追加されます。すべてのSnapManager for Hyper-Vソフトウェアコンポーネントをインストールして実行するには、Hyper-V親ホストがオペレーティングシステムとHyper-Vの最小要件を満たしていることを確認する必要があります。

* *対応オペレーティング・システム*
+
SnapManager for Hyper-Vは、次のオペレーティングシステムで実行されます。

+
** Windows Server 2008 R2 SP1
** Windows Server 2012 R2
** Windows Server 2012
** Windows Server 2016
** Windows Server 2019


* *サポートされている管理コンソール・オペレーティング・システム*
+
管理コンソールで次のオペレーティングシステムが実行されている必要があります。

+
** Windows Server 2008 R2 SP1
** Windows Server 2012 R2
** Windows Server 2012
** Windows Server 2016
** Windows Server 2019


* * Hyper-V要件*
+
詳細については、Microsoft TechNetライブラリの「Hyper-Vの概要」を参照してください。

* *国際化サポート*
+
SnapManager for Hyper-Vは、ドイツ語および日本語のオペレーティングシステムでテスト済みです。



* 関連情報 *

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：「Hyper-V」"]

http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]
