---
permalink: reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html 
sidebar: sidebar 
keywords: environment, hardware, software, ontap, license, licensing, requirement, install, snapmanager, hyper-v, windows, .net, 4.5 
summary: SnapManager for Hyper-Vをインストールするには、環境がハードウェア、ソフトウェア、ONTAP 、およびライセンスに関するすべての要件を満たしている必要があります 
---
= SnapManager for Hyper-Vをインストールするための要件の一覧です
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-Vをインストールするには、環境がハードウェア、ソフトウェア、ONTAP 、およびライセンスに関するすべての要件を満たしている必要がありますWindowsオペレーティングシステムと.Net 4.5の最小要件が満たされていない場合は、インストーラが停止します。



== Hyper-V親ホストの要件

Windows Server 2008 R2以降を実行するHyper-V親ホストが必要です。親ホストでHyper-Vロールを有効にしておく必要があります。Hyper-V親ホストにSnapDrive 7.1 for Windows以降をインストールしておく必要があります。



== SnapManager for Hyper-Vのダウンロード

ネットアップサポートサイトからSnapManager for Hyper-Vソフトウェアをダウンロードしておく必要があります。



== ストレージシステムの要件

ストレージシステムで適切なバージョンのONTAP ソフトウェアが実行されている必要があります。SnapManager for Hyper-Vのインストールには、ホストベースまたはストレージシステム単位のライセンスを使用できます



== ライセンス

Hyper-VでSnapManager を実行するには、適切なライセンスが必要です



== クレデンシャル

Hyper-V用にSnapManager をインストールして実行するための適切なクレデンシャルが必要です



== サービスアカウントと認証の要件

サービスアカウントが必要です。また、認証要件を満たしている必要があります。サービスアカウントを使用してホストにログインできる必要があります。また、そのアカウントには管理者権限が必要です。



== Webサービスのポート番号

使用可能なWebサービスのNet.Tcpポート番号が必要です。デフォルトのポート番号は808です。クラスタにSnapManager for Hyper-Vをインストールする場合は、すべてのノードで同じポート番号が使用されていることを確認する必要があります。
