---
permalink: reference-requirements-for-creating-a-dataset.html 
sidebar: sidebar 
keywords: specific, requirement, create, dataset, protect, data, host, cluster, snapmanager, hyper-v 
summary: データを保護するためにデータセットを作成する場合は、特定の要件を満たす必要があります。 
---
= データセットの作成要件
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データを保護するためにデータセットを作成する場合は、特定の要件を満たす必要があります。まず、Hyper-V用のSnapManager にホストまたはホストクラスタを追加してから、ホストまたはホストクラスタに仮想マシンを追加する必要があります。



== データセット名と概要

データセットに名前を付けるときは、サイトで命名規則を使用して、管理者がデータセットを検索して特定できるようにします。使用できる文字は次のとおりです。

* a ~ z
* A ~ Z
* 0～9
* _（アンダースコア）
* -（ハイフン）




== データセットリソース

仮想マシンなどのリソースをデータセットに追加する前に、Hyper-V用のSnapManager にホストまたはホストクラスタを追加する必要があります。

データセットには、ホスト、専用の仮想マシン、または共有の仮想マシンを追加できます。ホストを追加する場合は、そのホストに属するすべての仮想マシンを追加します。また、異なるホストに属する仮想マシンをデータセットに追加することもできます。仮想マシンは、複数のデータセットに属することができます。


NOTE: 同じホストクラスタに属する専用仮想マシンと共有仮想マシンは、同じデータセット内に存在することはできません。これらのタイプ原因 のリソースを単一のデータセットに追加すると、データセットのバックアップが失敗する可能性があります。



== 仮想マシンとONTAP LUN

構成ファイル、Snapshotコピー、VHDなど、仮想マシンに関連付けられたすべてのファイルは、ONTAP LUN上に存在する必要があります。



== データセットのリソース消費量

1つのホストで同時に実行できるアプリケーションと整合性のあるバックアップ処理は1つだけです。同じ仮想マシンが異なるデータセットに属している場合は、アプリケーションと整合性のあるデータセットのバックアップを同時にスケジュールしないでください。この場合、いずれかのバックアップ処理は失敗します。

データセットを作成するときは、特定のONTAP LUN上に存在するすべての仮想マシンを選択する必要があります。これにより、すべてのバックアップを1つのSnapshotコピー内にまとめることができ、ストレージシステム上で消費されるスペースを減らすことができます。
