---
permalink: task-change-the-snapinfo-directory-path.html 
sidebar: sidebar 
keywords: control, snapinfo, directory, path, setting, configuration, wizard, action, changing, change 
summary: SnapInfoディレクトリパス設定は、設定ウィザードまたはSnapInfo設定アクションを使用して制御できます。 
---
= SnapInfoディレクトリパスを変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapInfoディレクトリパス設定は、設定ウィザードまたは* SnapInfo設定*アクションを使用して制御できます。

.このタスクについて
SnapInfoディレクトリ設定は、Hyper-VのSnapManager のホストレベルで指定されますSnapManager for Hyper-Vは、NAS（SMB）ホストとSANホストをサポートしています。SANホストの場合は、SnapInfo設定がボリュームレベルで適用されます。NASホストの場合は、SMB共有レベルでSnapInfo設定が適用されます。

ストレージシステムのIPアドレスをSnapDrive for Windows TPSに追加した場合は、SnapManager for Hyper-Vで設定ウィザードを実行すると、SnapDrive for Windowsのストレージ設定が自動的に読み込まれますSnapDrive for Windows TPSが設定されていない場合は、SnapManager for Hyper-Vの[Manage Storage Connections]タブでストレージシステムのIPアドレスを指定する必要があります

.手順
. ナビゲーションペインで、[Menu](メニュー)、[Hosts](ホスト保護)の順にクリックします。
. SnapInfoディレクトリパスを変更するホストを選択します。
. [Actions]ペインで、[* SnapInfo settings]を選択します。
+
[* SnapInfo設定*（* SnapInfo Settings *）]ダイアログボックスが開きます。

. 表示されたオプションからストレージタイプを選択します。
+
|===
| オプション | 説明 


 a| 
SAN
 a| 
これがデフォルトのストレージタイプです。



 a| 
NAS
 a| 
このオプションは、SMB共有で使用します。

|===
. [* 参照 ] をクリックします。
+
[フォルダの参照]ウィンドウが開きます。

. SnapInfoストレージシステム（SAN）またはボリューム（NAS）を選択し、* OK *をクリックします。
+
表示されるホストは'ホスト・レベルで[ストレージ接続の管理]オプションを使用して登録されたストレージ・システムに対応するNAS共有です探している共有が表示されない場合は、「ストレージ接続の管理」が正しく設定されていることを確認してください。

. [* SnapInfo設定*（* SnapInfo Settings *）]ウィンドウで、[OK]をクリックします。

