---
permalink: task_importing_or_exporting_host_and_dataset_configuration_information.html 
sidebar: sidebar 
keywords: manage, host, management, console, multiple, import, export, information, dataset, consistency 
summary: ホストを管理する管理コンソールは1つに限定する必要がありますが、複数のコンソールから管理する必要がある場合は、ホストおよびデータセットの構成情報を1つのリモート管理コンソールから別のリモート管理コンソールにインポートしてエクスポートすることで、データの整合性を確保できます。 
---
= ホストとデータセットの設定情報をインポートまたはエクスポートする
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ホストを管理する管理コンソールは1つに限定する必要がありますが、複数のコンソールから管理する必要がある場合は、ホストおよびデータセットの構成情報を1つのリモート管理コンソールから別のリモート管理コンソールにインポートしてエクスポートすることで、データの整合性を確保できます。

SnapManager for Hyper-Vがインストールされているディレクトリには、設定情報をインポートしたりエクスポートしたりしないでください。SnapManager for Hyper-Vをアンインストールすると、このファイルは失われます。


NOTE: インポートとエクスポートウィザードを使用して、ホストとデータセットの設定を以前にエクスポートした設定に変更することができます。クラスタ環境でこの処理を実行する場合は、クラスタ内のすべてのノードで設定をインポートして、すべてのホストとデータセットの構成が同じになるようにする必要があります。

. ナビゲーションペインで、*保護*をクリックします。
. アクションペインで、*インポートおよびエクスポート*をクリックします。
+
インポートとエクスポートウィザードが表示されます。

. ウィザードの手順に従って、ホストとデータセットの構成情報をある管理コンソールから別の管理コンソールにエクスポートします。
+

NOTE: エクスポートファイルは、そのエクスポートファイルが実行された時点でのみ静的で最新のものです。

. ウィザードの手順に従って、ホストとデータセットの設定情報をデスティネーション管理コンソールにインポートします。

