---
permalink: task_restoring_a_virtual_machine_from_a_backup_copy.html 
sidebar: sidebar 
keywords: snapmanager, hyper-v, restore, single, virtual, machine, vm, recover, lost, damage, data, backup, copy, restoring 
summary: SnapManager for Hyper-Vでは、一度に1台の仮想マシン（VM）をリストアし、失われたデータや破損したデータをバックアップコピーからリカバリできます。 
---
= バックアップコピーからの仮想マシンのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SnapManager for Hyper-Vでは、一度に1台の仮想マシン（VM）をリストアし、失われたデータや破損したデータをバックアップコピーからリカバリできます。

次の情報が必要です。

* バックアップ名
* 設定情報
* スクリプト情報


代替ホストにリストアする場合は、元のVMが配置されていた物理コンピュータ上のCPUタイプが、VMをリストアする物理コンピュータと互換性がある必要があります。また、Hyper-V Managerを使用して、CPUタイプの異なるマシンへのリストアを許可することもできます。

ストレージのライブマイグレーション後は、最新のバックアップからリストアすることはできません。

Hyper-V仮想マシンのリストア処理を開始したときに、同じ仮想マシンの別のバックアップまたはリストアが進行中の場合は、処理が失敗します。

. ナビゲーションペインで、*回復*をクリックします。
. リストアする仮想マシンを選択します。
. バックアップペインで、リストアするバックアップコピーの名前を選択し、*リストア*をクリックします。
+
リストアウィザードが表示されます。

. ウィザードの手順に従って、仮想マシンのバックアップコピーをリストアします。
+
ウィザードを閉じても、リストア処理はキャンセルされません。SnapManager for Hyper-Vは、リストア処理を開始する前に仮想マシンの設定を検証します。仮想マシンの設定に変更があった場合は、警告が表示され、続行するかキャンセルするかを選択できます。



[ジョブ管理]ウィンドウでリストア処理のステータスを表示したり、[レポート管理]ウィンドウでレポートを表示して処理結果を確認したりできます。

* 関連情報 *

xref:reference_restoring_from_a_backup_after_failback.adoc[フェイルバック後のバックアップからのリストア]
