---
permalink: task_setting_up_a_snapinfo_lun.html 
sidebar: sidebar 
keywords: add, snapinfo, lun, snapmanager, hyper-v, store, dataset, backup, metadata, reside, ontap, setting, up 
summary: データセットバックアップメタデータを格納するには、Hyper-V用のSnapManager にSnapInfo LUNを追加する必要があります。SnapInfoパスは、ONTAP LUN上に実装する必要があります。これは、SnapManager for Hyper-Vが通常のバックアップの実行後にSnapInfoコピーのバックアップを作成するためです。 
---
= SnapInfo LUNをセットアップしています
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
データセットバックアップメタデータを格納するには、Hyper-V用のSnapManager にSnapInfo LUNを追加する必要があります。SnapInfoパスは、ONTAP LUN上に実装する必要があります。これは、SnapManager for Hyper-Vが通常のバックアップの実行後にSnapInfoコピーのバックアップを作成するためです。

SnapInfoパスは、Windows Server 2012クラスタを実行している場合は、Cluster Shared Volume（CSV；クラスタ共有ボリューム）に配置できます。専用の仮想マシンを管理する場合は、SnapInfoを専用のONTAP LUNに配置する必要があります。共有仮想マシンを管理する場合は、SnapInfoを共有のONTAP LUNに実装します。

. SnapDrive for Windowsを使用して、新しい共有ディスクを作成します。
+
.. Microsoft Cluster Services Group（Microsoftクラスタサービスグループ）を選択するオプションを指定する場合は、* Create a new cluster group.*（新しいクラスタグループを作成する*）を選択します
.. グループに「SMHV SnapInfo」という名前を付け、プロセスを完了します。


. Windowsフェイルオーバークラスタリング（WFC）を開き、新しいグループがオンラインになっていることを確認します。
. クラスタ内の各ノードにSnapManager for Hyper-Vをインストールします。
. 設定ウィザードを実行し、クラスタ内のすべてのノードにSnapInfo設定を適用します。
+
.. いずれかのホストを選択します。
.. ナビゲーションペインで、* Protection *>* Hosts *をクリックします。
.. [Actions]ペインで、設定ウィザードを実行します。
.. 新しく作成したLUNにSnapInfo設定を適用します。




設定ウィザードを実行すると、SnapInfoの設定がクラスタ内のすべてのノードにレプリケートされます。

* 関連情報 *

xref:reference_error_snapdrive_sddiscoveryfilesystemlistinfo_response_is_null.adoc[エラー：SnapDrive SDDiscoveryFileSystemListInfo応答がNULLです]
