---
permalink: task-recover-and-restore-from-a-disaster-recovery-failover.html 
sidebar: sidebar 
keywords: recover, disaster, snapmanager, hyper-v, fail, secondary, system, storage, powershell, restore, restoring, failover, recovery 
summary: 災害からリカバリするには、SnapManager for Hyper-Vをまずセカンダリストレージシステムにフェイルオーバーする必要があります。フェイルオーバーには、PowerShellの一連の手動手順が必要です。 
---
= ディザスタリカバリフェイルオーバーからリカバリおよびリストアを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
災害からリカバリするには、SnapManager for Hyper-Vをまずセカンダリストレージシステムにフェイルオーバーする必要があります。フェイルオーバーには、PowerShellの一連の手動手順が必要です。

.このタスクについて
ほとんどのバックアップはNASとSANの両方で別のホストにリストアできますが、Windows Server 2008 R2のcrash-consistentバックアップは別のホストにリストアできません。

.手順
. Data ONTAP 8.1.xを実行している場合は、セカンダリサイトで、SnapDrive for Windows MMCのTransport Protocol設定（TPS）にStorage Virtual Machine（SVM）情報を入力します。
. セカンダリストレージシステムから、すべてのLUNに接続します。
+
セカンダリストレージシステムがクラスタ化されている場合は、デスティネーションクラスタで使用可能なストレージグループの所有者ノードであるクラスタグループがオンラインのノードに移動し、そのノードからクラスタ内のすべてのLUNに接続します。LUNのマッピングについては、SnapDrive for Windowsのドキュメントを参照してください。

. 構成に応じて、次のいずれかの操作を実行します。
+
|===
| プライマリストレージシステムの状態 | 作業 


 a| 
スタンドアロンホスト（SAN）
 a| 
プライマリストレージシステム上で、同じタイプのすべてのマウントポイントとLUNに接続します。



 a| 
クラスタ化ホスト（SAN）
 a| 
クラスタグループがオンラインのノードから、クラスタ内のすべてのマウントポイントとLUNに接続します。



 a| 
Data ONTAP 8.1.xは、ソースFlexVol （SAN）上のVMをホストする1つのLUNで構成
 a| 
SnapMirror更新を正常に実行するには、バックアップを開始する前に、ソースFlexVol ボリューム上にサイズが小さい2つ目のLUN（10~100MB）を作成する必要があります。クラスタグループがオンラインのノードから、クラスタ内のすべてのマウントポイントとLUNに接続します。



 a| 
スタンドアロンホストまたはクラスタホスト（NAS）
 a| 
データ保護（DP）ボリュームをアンマウントし、DPボリュームを書き込み可能としてマウントします。ボリュームにRWX権限があることを確認してから、各ボリューム用のCIFS共有を作成します。

|===
. ご使用の環境に基づいてSnapInfoを再設定します。
+
|===
| 構成 | 作業 


 a| 
SAN
 a| 
最後のSnapshotコピーからSnapInfo LUNをリストアします。



 a| 
NAS
 a| 
SnapInfoディレクトリをマウントします。

|===
+
NASの場合、アクセスが拒否されたエラーが発生した場合、または公開されているSMB共有の場所を参照できない場合は、共有上でアクセス制御リストのリセットが必要になることがあります。

+

NOTE: これは、通常、System Center Virtual Machine Manager（SCVMM）コンソールとData ONTAP SMI-Sエージェントを使用する場合に発生します。

. SnapManager for Hyper-V MMCでセカンダリストレージシステムまたはクラスタを追加し、SnapInfoパスを使用して設定します。
. 次のコマンドレットを入力します。
+
.. 「Get-VMsFromBackup」と入力して、バックアップメタデータ内に存在するVMのリストを取得します。
.. 「Get-Backup」と入力して、各VMのバックアップ・コピーを取得します。


. リストアするには'Restore-Backup'をVM GUIDとともに使用し'バックアップ・コピーを次のパラメータで使用します
+
|===
| リストア元 | 入力するコマンド 


 a| 
代替ホスト
 a| 
「Restore - Backup - Server」「Secondary_host_system_or_cluster_name - DisableVerifySnapshot - RestoreToAlternateHost



 a| 
リストされたバックアップ
 a| 
「Restore - Backup - Server - VirtualMachinePath - SnapShotFilePath @ VHD」を参照してください

|===
+
「@vhd」の場合、VMに複数のVHDが含まれている可能性があります。それぞれのVHDに指定したソースパスとデスティネーションパスのペアを両方入力するようにしてください。

. セカンダリホストシステムがクラスタの場合は、次の手順を実行します。
+
.. VMを配置するLUNが、クラスタグループを所有するクラスタノード上でオンラインであることを確認します。
.. フェイルオーバー用のPowerShellコマンドレットを使用して、VMの高可用性を確保します。






== フェイルオーバーの例

次の例は、SMHVがクラスタを2つセットアップしたものです。この2つのクラスタはプライマリサイトで、hv_cluster-01がセカンダリサイトです。

[listing]
----
PS C:\> Get-VMsFromBackup -Server hv-19-cluster

winxp-x64c-135                593ABA72-B323-4AF7-9AC6-9514F64C0178
csv1-xp-3                     59B85C68-BAFA-4A49-8E85-A201045843F7
vm-w2k8r2sp1                  5A248757-872B-4FE7-8282-91C8E9D45CF9
um10_11_dr                    5AC1B2A8-6603-4F90-98F5-4F2F435AB0C2
winxp-x64c-30                 5B47D3CF-5D96-495D-9BAB-FB394392CF31
winxp-x64c-126                5B57EED1-B4F1-45A3-A649-24C6947CB79C
winxp-x64c-118                5B5D417B-70DC-427C-94BB-97FF81C5B92B
winxp-x64c-122                5BEE26B8-BE57-4879-A28E-9250A6A5EEFC
csv4-w2k3-19                  5D0613E5-B193-4293-8AAD-F8B94A5D851F

PS C:\> Get-Backup -Server hv-19-cluster -ResourceName um10_11_dr

BackupName    : smhv-ccb-ds_04-10-2012_10.37.58
RetentionType : hourly
DatasetName   : smhv-ccb-ds
BackupId      : smhv-ccb-ds_04-10-2012_10.37.58
BackupTime    : 4/10/2012 10:37:58 AM
BackupType    : Application consistent
BackedupVMs   : {um10_11_dr}

PS C:\> Restore-Backup -Server hv-19-cluster -ResourceName
um10_11_dr -BackupName smhv-ccb-ds_04-10-2012_10.37.58
-DisableVerifySnapshot -RestoreToAlternateHost
----
次の例は、SANのリストア処理で代替パスに接続しています。N：\がデスティネーションで、I：\がソースLUNのパスです。

[listing]
----
PS C:\> Restore-Backup -Resourcename dr-san-ded1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName san_dr_09-11-2013_10.57.31 -Verbose
-VirtualMachinePath "N:\dr-san-ded1" -SnapshotFilePath "N:\dr-san-ded1" -VHDs @(@{"SourceFilePath" = "I:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1.vhdx"; "DestinationFilePath" = "N:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1"})
----
次の例は、\\172.17.162.174\がソースSMB共有パスで、\\172.17.175.82\がデスティネーションSMB共有パスである代替パスへのNASリストア操作を示しています。

[listing]
----
PS C:\> Restore-Backup -Resourcename vm_claba87_cifs1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName ag-DR_09-09-2013_16.59.16 -Verbose
-VirtualMachinePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -SnapshotFilePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -VHDs @(@{"SourceFilePath" = "\\172.17.162.174\vol_test_src_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"; "DestinationFilePath" = "\\172.17.175.82\vol_new_dest_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"})
----
* 関連情報 *

https://library.netapp.com/ecm/ecm_download_file/ECMP1368826["『Data ONTAP 8.2 Data Protection Online Backup and Recovery Guide for 7-Mode』"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["ネットアップのマニュアル： SnapDrive for Windows （現在のリリース）"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["SMB/CIFS Reference 』を参照してください"]
